apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    run: udagram-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
  type: LoadBalancer
  selector:
    app: udagram-frontend
